"""add city, date_time unique together constraint to Temperature model

Revision ID: 5525f7f37527
Revises: 6c65c3831e29
Create Date: 2026-08-19 19:25:20.266248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5525f7f37527"
down_revision: Union[str, Sequence[str], None] = "6c65c3831e29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("temperatures", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_city_date_time", ["city_id", "date_time"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("temperatures", schema=None) as batch_op:
        batch_op.drop_constraint("uq_city_date_time", type_="unique")

    # ### end Alembic commands ###
