"""unique city name

Revision ID: 969e34a03884
Revises: ac66fbe1e934
Create Date: 2026-08-18 19:32:01.221962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969e34a03884'
down_revision: Union[str, Sequence[str], None] = 'ac66fbe1e934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_cities_name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cities_name', type_='unique')

    # ### end Alembic commands ###
