"""make temperature field type float in Temperature model

Revision ID: c09bf975264a
Revises: 5525f7f37527
Create Date: 2026-08-19 19:46:28.591520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09bf975264a'
down_revision: Union[str, Sequence[str], None] = '5525f7f37527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperatures', schema=None) as batch_op:
        batch_op.alter_column('temperature',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperatures', schema=None) as batch_op:
        batch_op.alter_column('temperature',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
